CREATE TABLE TB_TOPIC
(
    ID         BIGSERIAL PRIMARY KEY,
    TITLE      VARCHAR(200) NOT NULL,
    CONTENT    TEXT         NOT NULL,
    USER_ID    BIGINT       NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TOPIC_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID)
);