CREATE TABLE TB_QUIZ_QUESTION
(
    ID             BIGSERIAL PRIMARY KEY,
    TOPIC_ID       BIGINT  NOT NULL,
    QUESTION_TEXT  TEXT    NOT NULL,
    OPTION_A       TEXT    NOT NULL,
    OPTION_B       TEXT    NOT NULL,
    OPTION_C       TEXT    NOT NULL,
    OPTION_D       TEXT    NOT NULL,
    OPTION_E       TEXT    NOT NULL,
    CORRECT_OPTION CHAR(1) NOT NULL,
    EXPLANATION    TEXT,
    CONSTRAINT FK_QUIZ_TOPIC FOREIGN KEY (TOPIC_ID) REFERENCES TB_TOPIC (ID) ON DELETE CASCADE
);